// <auto-generated />
using System;
using CoDodoApi.Services.EFService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoDodoApi.Migrations
{
    [DbContext(typeof(CoDodoDbContext))]
    [Migration("20260225203248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoDodoApi.Services.EFService.EFProcess", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("UriForAssignment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UriForAssignment");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Capability");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Company");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDate");

                    b.Property<int>("HourlyRateInSEK")
                        .HasColumnType("int")
                        .HasColumnName("HourlyRateInSEK");

                    b.Property<string>("NameOfSalesLead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NameOFSalesLead");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset>("UpdatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("UpdatedDate");

                    b.HasKey("Name", "UriForAssignment");

                    b.HasIndex("Name", "UriForAssignment")
                        .IsUnique();

                    b.ToTable("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
