// <auto-generated />
using System;
using CoDodoApi.Services.EFService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoDodoApi.Migrations
{
    [DbContext(typeof(CoDodoDbContext))]
    [Migration("20260225173928_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoDodoApi.Services.EFService.EFProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Capability");

                    b.Property<DateOnly>("GenerationDate")
                        .HasColumnType("date")
                        .HasColumnName("GenerationDate");

                    b.Property<int>("HourlyRate")
                        .HasColumnType("int")
                        .HasColumnName("HourlyRate");

                    b.Property<DateOnly>("LastUpdate")
                        .HasColumnType("date")
                        .HasColumnName("LastUpdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Opportunity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Opportunity");

                    b.Property<string>("SalesLead")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SalesLead");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Proceses");
                });
#pragma warning restore 612, 618
        }
    }
}
